### ISSUE TITLE
Exporter still exports even if Zookeeper is unavailable

### ISSUE THREAD

**Issue by StephanErb** [carlpett/zookeeper_exporter#7]
The exporter is maintaining the metric `zk_up` to indicate if scraping was successful or not. This is somewhat duplicating the [Prometheus built-in `up`](https://prometheus.io/docs/concepts/jobs_instances/#automatically-generated-labels-and-time-series) metric that is automatically defined for each scrape target. 

I believe that this exporter should return a HTTP status code `502` to indicate scraping has failed. As a user of this exporter I could then rely on my generalised `up` alert without having to define a special alert just for Zookeeper.

**Comment by carlpett** [comment]
Thanks for the suggestion! There are two recommendations regarding this in the "Writing Exporters" docs: https://prometheus.io/docs/instrumenting/writing_exporters/#failed-scrapes, one is the current implementation (having a `zk_up` metric) and the other is to return HTTP 5xx. 

The deciding factor when writing the exporter was that failing the entire scrape would make it impossible in an alert to determine if the failure is in the exporter itself or in Zookeeper. 

But I can see that this is mainly personal preference. Maybe having a flag for failing the scrape instead of toggling a metric?

**Comment by StephanErb** [comment]
Ah, I wasn't aware of that particular section of the guidelines. Thanks for the pointer.

Yeah, having a flag sounds like a reasonable choice.

**Comment by carlpett** [comment]
Closing this - over the years I've come to value seeing the exporter's metrics even when the backing system is down, and it is a common enough pattern that I don't think customizability is warranted.
